baseurl = "https://ops.m114.org/"
languageCode = "zh-cn"
title = "ops"
theme = "blackburn"

# Shown in the side menu
copyright = "&copy; 2014-2018. All rights reserved."
canonifyurls = true
paginate = 10

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "records of learning."
  brand = "Ops"
  disqus = "vinsoncou"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  dateFormat = "2006/01/02, 15:04"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 1
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "Topics"
    pre = "<i class='fa fa-folder fa-fw'></i>"
    weight = 3
    identifier = "topic"
    url = "/topics/"
  [[menu.main]]
    name = "Tags"
    pre = "<i class='fa fa-tags fa-fw'></i>"
    weight = 4
    identifier = "tag"
    url = "/tags/"

[social]
github = "vinsonzou"
